### ISSUE TITLE
Please help to recommend some feature configs and parameter settings

### ISSUE THREAD

**Issue by apphpp** [xmb-cipher/fofe-ner#6]
Hi, could you please give some recommended feature configs,  and parameter setting to achieve the performance in this paper?    For example,  I tried the default setting given in the code, F1 of "all word-level features" is about 82.6, vs 88.96 in your work.   Thanks so much :)

**Comment by xmb-cipher** [comment]
Thanks for your interest. 

We used 
1.  word embedding of 128d, 
2. 3 FC layer with 512 nodes,
3. drop rate of 0.5 at the beginning, decreased a little bit after every epoch

Embedding is fine-tuned instead of jointly trained. Embedding lr is 1/4 of global lr. 
The quality of initial embedding is also important. We ran word2vec on English Gigaword for 10 days.

**Comment by apphpp** [comment]
Thanks, I'v tried the above settings except for the initial word embddings for now, but still the F1 is around 83 on conll03 eng, still a big gap , I'm now trying to repeat your embedding initialization method. By the way, is their significant performance gap between "fofe_mention_net_v3"  and  "fofe_mention_net" in your given code?
